/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import static org.junit.Assert.assertEquals;

import org.junit.After;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

public class CorreiosTest {
   
	private String objetoPostado = "BE315309539BR";
	private String objetoEntregue = "PS526891317BR";
	private String objetoNaoExistente = "PP170914586BR";
	private String objetoNaoRetiradoCorreio = "AA123456789BR";
	private String expectedMessageObjetoInexistente = "O nosso sistema não possui dados sobre o objeto informado.";
	private String expectedMessageObjetoNaoRetiradoCorreio = "Destinatário não retirou objeto na Unidade dos Correios";
	private String expectedMessageObjetoPostado = "Objeto postado";
	private String expectedMessageObjetoEntregue = "Objeto entregue ao destinatário";
	private WebDriver driver;
	
	@BeforeClass
	public static void setUpClass() {
		System.setProperty("webdriver.chrome.driver", System.getProperty("user.dir") + "/driver/chromedriver");
	}
	
	@Before
	public void setUpTest() {
		driver = new ChromeDriver();
		driver.get("https://www2.correios.com.br/sistemas/rastreamento/");
		driver.manage().window().maximize();
	}
	
	@After
	public void closeTest() {
		driver.close();
	}
	
	@Test 
	public void test_ObjetoInexistente() {
		WebElement textArea = buildTextArea(driver, "//*[@id=\"objetos\"]");
		textArea.sendKeys(objetoNaoExistente);
		
		WebElement button = driver.findElement(By.xpath("//*[@id=\"btnPesq\"]"));
		button.click();
		
		WebElement returnMessage = driver.findElement(By.xpath("/html/body/div[1]/div[3]/div[2]/div/div/div[2]/div[2]/div[1]"));
		assertEquals(expectedMessageObjetoInexistente, returnMessage.getText());
    }
	
	@Test
	public void test_ObjetoNaoRetiradoCorreio() {
		WebElement textArea = buildTextArea(driver, "//*[@id=\"objetos\"]");
		textArea.sendKeys(objetoNaoRetiradoCorreio);
		
		WebElement button = driver.findElement(By.xpath("//*[@id=\"btnPesq\"]"));
		button.click();
		
		WebElement returnMessage = driver.findElement(By.xpath("/html/body/div[1]/div[3]/div[2]/div/div/div[2]/div[2]/div[3]/div[1]/div[2]/strong"));
		assertEquals(expectedMessageObjetoNaoRetiradoCorreio, returnMessage.getText());
	}
	
	@Test
	public void test_ObjetoNaoChegou() {
		WebElement textArea = buildTextArea(driver, "//*[@id=\"objetos\"]");
		textArea.sendKeys(objetoPostado);
		
		WebElement button = driver.findElement(By.xpath("//*[@id=\"btnPesq\"]"));
		button.click();
		
		WebElement returnMessage = driver.findElement(By.xpath("/html/body/div[1]/div[3]/div[2]/div/div/div[2]/div[2]/div[3]/div[1]/div[2]/strong"));
		assertEquals(expectedMessageObjetoPostado, returnMessage.getText());
	}
	
	@Test
	public void test_ObjetoEntregue() {
		WebElement textArea = buildTextArea(driver, "//*[@id=\"objetos\"]");
		textArea.sendKeys(objetoEntregue);
		
		WebElement button = driver.findElement(By.xpath("//*[@id=\"btnPesq\"]"));
		button.click();
		
		WebElement returnMessage = driver.findElement(By.xpath("/html/body/div[1]/div[3]/div[2]/div/div/div[2]/div[2]/div[3]/div[1]/div[2]/strong"));
		assertEquals(expectedMessageObjetoEntregue, returnMessage.getText());
	}

	private WebElement buildTextArea(WebDriver driver, String xpath) {
		WebDriverWait wait = new WebDriverWait(driver, 10);
		return wait.until(ExpectedConditions.elementToBeClickable(driver.findElement(By.xpath(xpath))));
	}
	
}
